### ISSUE TITLE
Refactorizar ds1_template

### ISSUE THREAD

**Issue by DavidC0rtes** [DavidC0rtes/sige#26]
**Describir el problema que se quiere solucionar**
Necesitamos refactorizar el template para poder pasar a integrar todas las demás vistas. Con refactorizar me refiero a volverlo un [CardLayout](https://docs.oracle.com/javase/8/docs/api/java/awt/CardLayout.html) para que así se pueda cambiar entre los distintos menús.

**Describir la solución que se quiere dar**
Arriba

**Soluciones alternativas que se han considerado (opcional)**
Un TabbedPane? En ese caso el menú pasaría a la parte de arriba del frame(creo).

**Conexto adicional**
Todo el proyecto depende de esta tarea.

**Comment by daveybtw** [comment]
Se creo un pull request con los cambios realizados.
