### ISSUE TITLE
Implementar permisos

### ISSUE THREAD

**Issue by DavidC0rtes** [DavidC0rtes/sige#35]
**Describir el problema que se quiere solucionar**
Como tal, aún no se ha implementado el acceso a las distintas interfaces condicionado al rol del usuario actual.

**Describir la solución que se quiere dar**
Aprovechándonos de que utilizamos un JCardLayout se me ocurre que se tenga una lista de las interfaces a las que se puede acceder dependiendo del rol y esas son las que se mostrarían en el menú del dashboard.

**Conexto adicional**
![image](https://user-images.githubusercontent.com/29616613/99883525-0756a480-2bf6-11eb-96e9-f771f4bcf5dc.png)

**Comment by camilojm27** [comment]
Para evitar repetir código estoy cambiando los layouts del Dashboard así no tenemos que crear un dashboard para cada rango sino que podríamos remover y agregar los ítems que necesita cada uno y como es un layout se reorganizan solos.

Mas ratito subo el update

**Comment by DavidC0rtes** [comment]
Implementado en #37

> Para evitar repetir código estoy cambiando los layouts del Dashboard así no tenemos que crear un dashboard para cada rango sino que podríamos remover y agregar los ítems que necesita cada uno y como es un layout se reorganizan solos.
> 
> Mas ratito subo el update

Así también la pensé y la implementé, dependiendo del rol del usuario se agrega o no el panel. Me avisas cuando subas lo tuyo

**Comment by DavidC0rtes** [comment]
Listo #38
